services:
  pantograph:
    image: pantograph:latest
    env_file:
      - .env
    build: .
    volumes:
      - "./uploads:/app/uploads"
      - "./data:/app/data"
    expose:
      - "5001"
    networks:
      - web_network
networks:
  web_network:
    external: true